In [1]:
import sys
sys.version

'3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)]'

# 머신러닝
- 기계에게 규칙을 찾아달라고 하기
- 규칙을 찾고 싶은 데이터가 필요 > 크롤링, 데이터 제공 사이트, 회사 내부 DB 등을 사용

In [ ]:
# 기계가 규칙을 잘 찾는지 확인하기
# 미스터리 사인

In [ ]:
# Question1
# 문제를 지정하고, 데이터 직접 만들기
# 규칙 : 큰 수 + 두 수의 차
# 22 ? 7 = 37

In [ ]:
# 데이터 수집

In [12]:
list1 = [] #저장 용도로 만들어진 공간
for i in range(100):
    for j in range(100):
        result = (i + (i-j)) if i > j else (j + (j-i))
        list1.append([i, j, result])
        
list1

[[0, 0, 0],
 [0, 1, 2],
 [0, 2, 4],
 [0, 3, 6],
 [0, 4, 8],
 [0, 5, 10],
 [0, 6, 12],
 [0, 7, 14],
 [0, 8, 16],
 [0, 9, 18],
 [0, 10, 20],
 [0, 11, 22],
 [0, 12, 24],
 [0, 13, 26],
 [0, 14, 28],
 [0, 15, 30],
 [0, 16, 32],
 [0, 17, 34],
 [0, 18, 36],
 [0, 19, 38],
 [0, 20, 40],
 [0, 21, 42],
 [0, 22, 44],
 [0, 23, 46],
 [0, 24, 48],
 [0, 25, 50],
 [0, 26, 52],
 [0, 27, 54],
 [0, 28, 56],
 [0, 29, 58],
 [0, 30, 60],
 [0, 31, 62],
 [0, 32, 64],
 [0, 33, 66],
 [0, 34, 68],
 [0, 35, 70],
 [0, 36, 72],
 [0, 37, 74],
 [0, 38, 76],
 [0, 39, 78],
 [0, 40, 80],
 [0, 41, 82],
 [0, 42, 84],
 [0, 43, 86],
 [0, 44, 88],
 [0, 45, 90],
 [0, 46, 92],
 [0, 47, 94],
 [0, 48, 96],
 [0, 49, 98],
 [0, 50, 100],
 [0, 51, 102],
 [0, 52, 104],
 [0, 53, 106],
 [0, 54, 108],
 [0, 55, 110],
 [0, 56, 112],
 [0, 57, 114],
 [0, 58, 116],
 [0, 59, 118],
 [0, 60, 120],
 [0, 61, 122],
 [0, 62, 124],
 [0, 63, 126],
 [0, 64, 128],
 [0, 65, 130],
 [0, 66, 132],
 [0, 67, 134],
 [0, 68, 136],
 [0, 69, 138],
 [0, 70, 140],


In [4]:
# 데이터 전처리
# 머신러닝 모델에 학습할 형식으로 변환 
# DataFrame, Series, np.array 많이 사용 => 계산 가능

In [23]:
import pandas as pd
data1 = pd.DataFrame(list1, columns=['N1','N2','Result'])
data1.head()

N1  N2  Result
0   0   0       0
1   0   1       2
2   0   2       4
3   0   3       6
4   0   4       8

In [26]:
# 빠른 연산을 위해 벡터 표현방식을 사용
# 문제(X) : 대문자 : 데이터가 2줄 이상 (2차원 이상)
# 정답(y) : 소문자 : 데이터가 1줄 (1차원)

X = data1.loc[:,'N1':'N2']
y = data1.loc[:,'Result']

In [29]:
# 학습
# 머신러닝 모델이 규칙을 찾게 해주기

# 사용할 모델 불러오기
from sklearn.ensemble import RandomForestRegressor
random_forest = RandomForestRegressor()

# 규칙 찾게하기
# 가지고 있는 전체 데이터를 살펴보고 문제로 정답을 도출할 수 있는 규칙 1가지 찾기
# 여러가지 규칙 중 제일 적합한 1가지를 가지고 온 상태
random_forest.fit(X, y)

RandomForestRegressor()

In [33]:
# 예측하기
# 찾은 규칙을 토대로 입력한 데이터의 정답 예측해보기
#random_forest.predict([[22,7]])
# 이중 리스트를 사용하는 이유
# X 형식과 같은 형식으로 데이터를 입력
random_forest.predict(pd.DataFrame([[22,7]], columns=['N1','N2']))

array([36.91])

In [ ]:
# 분홍색 경고창 -> 무시해도 상관 없음
# 약간의 문법 오류 -> 교쳐서 실행시켜 줌
# 버전에 따라 달라지는 코드/실행방식 > 일단 실행은 시켜줄테니 수정해! 

In [ ]:
#데이터 생성
list1 = [] #저장 용도로 만들어진 공간
for i in range(100):
    for j in range(100):
        result = (i + (i-j)) if i > j else (j + (j-i))
        list1.append([i, j, result])
#데이터 전처리
import pandas as pd
data1 = pd.DataFrame(list1, columns=['N1','N2','Result'])
X = data1.loc[:,'N1':'N2'] # 문제
y = data1.loc[:,'Result'] # 결과

# 모델 가져오기
from sklearn.ensemble import RandomForestRegressor
random_forest = RandomForestRegressor()

# 데이터 학습
random_forest.fit(X, y)

# 규칙으로 통해 입력한 데이터의 닶 예측하기 
random_forest.predict([[22,7]])

In [39]:
# Question2
# 규칙 : (큰 수 / 작은 수)의 나머지
# 4 ? 17 = 1
list2 = []

for i in range(100):
    for j in range(100):
        try:
            result1 = (i % j ) if i > j else ( j % i )
            list2.append([i, j, result1])
        except : 
            ZeroDivisionError
    
data2 = pd.DataFrame(list2, columns=['N1','N2','Result'])

X = data2.loc[:,'N1':'N2'] 
y = data2.loc[:,'Result']

random_forest.fit(X, y)
random_forest.predict([[4,17]])

C:\Users\gjaischool1\anaconda3\envs\machine\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([1.15])

In [41]:
# 선생님 풀이

list2 = []
for i in range(1,200):
    for j in range(1,200):
        result = (i%j) if i > j else (j%i)
        list2.append([i,j,result])

data2 = pd.DataFrame(list2, columns = ['N1','N2','Result'])
data2.head()


X = data2.loc[:,['N1','N2']]
y = data2.loc[:,'Result']

from sklearn.ensemble import RandomForestRegressor
random_forest = RandomForestRegressor()

random_forest.fit(X,y)

random_forest.predict([[4,18]])

C:\Users\gjaischool1\anaconda3\envs\machine\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([0.96])